%Jenis filter 2 : FIR (finite) dan IIR (infinite) [IR = Impulse Range]
%memakai fdatool
[a,fs] = audioread('output2.wav');

Hd = FilterCode;
%FILTERCODE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 16-Apr-2018 11:34:48

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fstop1 = 690;             % First Stopband Frequency
Fpass1 = 700;             % First Passband Frequency
Fpass2 = 775;             % Second Passband Frequency
Fstop2 = 800;             % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

out = filter(Hd,a);
figure(2);
subplot(2,1,1);
plot(a)
subplot(2,1,2);
plot(out)
% [EOF]
